[package]
name = "tsumiki-client"
version = "0.1.0"
edition = "2024"

[dependencies]
tsumiki-world = { path = "../world" }
tsumiki-protocol = { path = "../protocol" }
bevy = "0.19.1"
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
parley = { version = "0.9.0", default-features = false }
